# Customizations.

# Grab the GTX1080Ti, RX550 for passthrough. The GTX1070 is left to be used with vgpu.
softdep nvidia* pre: vfio_pci
options nvidia* ids=10de:1b81
options vfio_pci ids=10de:1b06,1002:0b04

# Replaced with zenpower.
blacklist k10temp
