# /etc/modules is obsolete and has been replaced by /etc/modules-load.d/.
# Please see modules-load.d(5) and modprobe.d(5) for details.
#
# Updating this file still works, but it is undocumented and unsupported.

# Customizations.

vfio
vfio_iommu_type1
vfio_pci
vfio_virqfd
