keepalive 8 24

route-nopull
route 10.8.40.0 255.255.255.0 vpn_gateway 2100
route 10.8.47.0 255.255.255.0 vpn_gateway 2100
route 10.8.58.0 255.255.255.0 vpn_gateway 2000
# Ensure strong E/S model routing works with just `bind` on the interface address.
route 0.0.0.0 0.0.0.0 vpn_gateway 2000
# route-ipv6 gilgamesh-40.gilgamesh.cc net_gateway 0
# route-ipv6 gilgamesh-58.gilgamesh.cc net_gateway 0
# route-ipv6 2000::/3 vpn_gateway 2000

client
proto udp
explicit-exit-notify
remote gilgamesh-58.gilgamesh.cc 1194
dev tun-58
resolv-retry infinite
nobind
persist-key
# persist-tun

remote-cert-tls server
verify-x509-name server_QzlvYRJP3BewfPy4 name
auth SHA256
auth-nocache
cipher AES-128-GCM
ignore-unknown-option data-ciphers
data-ciphers AES-128-GCM
ncp-ciphers AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
tls-ciphersuites TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256
verb 3
