# DNS leaks: Linux. May require `ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf`. May require manually positioning the `update-systemd-resolved` script.
script-security 2
setenv PATH /usr/bin
up /etc/openvpn/update-systemd-resolved
up-restart
down /etc/openvpn/update-systemd-resolved
down-pre
dhcp-option DOMAIN-ROUTE .

keepalive 8 24

dhcp-option DNS 208.67.222.222
dhcp-option DNS 208.67.220.220
dhcp-option DNS 1.1.1.1
dhcp-option DNS 8.8.8.8
dhcp-option DNS 2606:4700:4700::1001
dhcp-option DNS 2606:4700:4700::1111

route-nopull
route gilgamesh-40.gilgamesh.cc 255.255.255.255 net_gateway 0
route gilgamesh-58.gilgamesh.cc 255.255.255.255 net_gateway 0
route 10.8.40.0 255.255.255.0 vpn_gateway 2100
route 10.8.47.0 255.255.255.0 vpn_gateway 2100
route 10.8.58.0 255.255.255.0 vpn_gateway 2000
route 0.0.0.0 0.0.0.0 vpn_gateway 0
route-ipv6 gilgamesh-40.gilgamesh.cc net_gateway 0
route-ipv6 gilgamesh-58.gilgamesh.cc net_gateway 0
route-ipv6 2000::/3 vpn_gateway 0

route 18.172.0.0 255.254.0.0 net_gateway 0
route 18.238.0.0 255.254.0.0 net_gateway 0

client
proto udp
explicit-exit-notify
remote gilgamesh-58.gilgamesh.cc 1194
dev tun-58
resolv-retry infinite
nobind
persist-key
# persist-tun

remote-cert-tls server
verify-x509-name server_QzlvYRJP3BewfPy4 name
auth SHA256
auth-nocache
cipher AES-128-GCM
ignore-unknown-option data-ciphers
data-ciphers AES-128-GCM
ncp-ciphers AES-128-GCM
tls-client
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
tls-ciphersuites TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256
verb 3
