#!/usr/bin/env bash
# Bind to interface doesn't work for some reason. Make sure the default route is on a VPN!
#	--interface=tun-31 \
aria2c \
	-u 16 \
	--seed-time 0 \
	--stream-piece-selector=inorder \
	--bt-prioritize-piece=head=64M \
	--bt-load-saved-metadata \
	--bt-request-peer-speed-limit=1M \
	"$@"
