#!/usr/bin/env bash
# Generates various IDs.
if [ "$1" = "password" ]; then
	id="!1Aa$(tr -dc '02-9a-z' < /dev/urandom | head -c 20)"
elif [ "$1" = "uuid" ]; then
	id=$(uuidgen)
elif [ "$1" = "totp" ]; then
	# Useful for generating 2fa codes provided an original time-based key (e.g. from Slack).
	id=$(oathtool -b --totp "$2")
fi
echo "$id"
clip "$id"
