#!/usr/bin/env bash
# Starts a graphical session (e.g. not SSH) to the remote.

# Get current resolution and FPS.
resolution_string=$(kscreen-doctor -o | grep enabled -A5 | grep Modes: | xargs -n1 | grep "*" | sed -E "s/.+\://g" | sed -E "s/\*//g" | tr -dc "[:alnum:]\n\r\.@" | sed -E "s/.*m(.+)m.*/\1/g")
resolution_x=$(echo $resolution_string | sed -E "s/x.+//g")
resolution_y=$(echo $resolution_string | sed -E "s/.+x//g" | sed -E "s/@.+//g")
resolution_fps=$(echo $resolution_string | sed -E "s/.+@//g" | xargs printf "%.0f\n")
echo $resolution_string
echo $resolution_x
echo $resolution_y
echo $resolution_fps

host=$1
if [ "$host" = "34" ]; then
	SDL_VIDEODRIVER=wayland scrcpy -f --tcpip=10.8.31.34 --no-audio
elif [ "$host" = "42" ]; then
	moonlight stream --resolution ${resolution_x}x${resolution_y} --fps $resolution_fps 10.8.40.42 Desktop
elif [ "$host" = "43" ]; then
	moonlight stream --resolution ${resolution_x}x${resolution_y} --fps $resolution_fps 10.8.45.43 default
elif [ "$host" = "48" ]; then
	SDL_VIDEODRIVER=wayland scrcpy -f --tcpip=10.8.40.48 --orientation 270
elif [ "$host" = "49" ]; then
	moonlight stream --resolution ${resolution_x}x${resolution_y} --fps $resolution_fps 10.8.45.49 default
elif [ "$host" = "50" ]; then
	SDL_VIDEODRIVER=wayland scrcpy -f --tcpip=10.8.31.50 --no-audio
elif [ "$host" = "57" ]; then
	SDL_VIDEODRIVER=wayland scrcpy -f --tcpip=10.8.31.57 --no-audio
fi
