#!/usr/bin/env bash
if [ "$1" = "trackpad" ]; then
	# xdotool mousemove 0 0
	# xdotool mousemove_relative 9999 100
	echo mouseto 1 0.1 | dotoolc
	if ! lsmod | grep -q hid_multitouch; then
		sudo modprobe hid_multitouch
		echo Enabled trackpad.
	else
		sudo modprobe -r hid_multitouch
		echo Disabled trackpad.
	fi
elif [ "$1" = "radio" ]; then
	if ! lsmod | grep -q iwlwifi; then
		sudo modprobe iwlwifi
		sudo modprobe iwlmld
		sudo modprobe btintel_pcie
		echo Enabled radios.
	else
		sudo modprobe -r btintel_pcie
		sudo modprobe -r iwlmld
		sudo modprobe -r iwlwifi
		echo Disabled radios.
	fi
elif [ "$1" = "nightlight" ]; then
	# Not used anymore.
	qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut "Toggle Night Color"
elif [ "$1" = "theme" ]; then
	# By default, toggles the theme and night light.
	# Themes trigger twice due to chromium bug not adjusting theme on first trigger.
	# gx toggle nightlight
	current_theme=$(kreadconfig6 --group KDE --key LookAndFeelPackage)
	if [ "$current_theme" = "org.kde.breezedark.desktop" ]; then
		lookandfeeltool -a org.kde.breeze.desktop
		sleep 0.4
		lookandfeeltool -a org.kde.breeze.desktop
		plasma-apply-wallpaperimage $(realpath ~/main.syncthing/monochrome/theme/intent-1650x2200.avif)
		echo Enabled light theme.
	else
		lookandfeeltool -a org.kde.breezedark.desktop
		sleep 0.4
		lookandfeeltool -a org.kde.breezedark.desktop
		plasma-apply-wallpaperimage $(realpath ~/main.syncthing/monochrome/theme/intent-dark-1650x2200.avif)
		echo Enabled dark theme.
	fi
elif [ "$1" = "vpn" ]; then
	if systemctl -q is-active gilgamesh-58.ovpn; then
		gx vpn 47
		echo Enabled gilgamesh-47.ovpn.
	elif systemctl -q is-active gilgamesh-47.ovpn; then
		gx vpn 58
		echo Enabled gilgamesh-58.ovpn.
	fi
elif [ "$1" = "syncthing" ]; then
	if [ "`syncthing cli config folders ifzzk-usnva paused get`" = "true" ]; then
		syncthing cli config folders ifzzk-usnva paused set false
		echo Enabled Syncthing.
	else
		syncthing cli config folders ifzzk-usnva paused set true
		echo Disabled Syncthing.
	fi
fi
