#!/usr/bin/env bash
if [ "$1" = "trackpad" ]; then
	xdotool mousemove 0 0
	xdotool mousemove_relative 9999 100
	if ! lsmod | grep -q hid_multitouch; then
		sudo modprobe hid_multitouch
		echo Enabled trackpad.
	else
		sudo modprobe -r hid_multitouch
		echo Disabled trackpad.
	fi
elif [ "$1" = "radio" ]; then
	if ! lsmod | grep -q iwlwifi; then
		sudo modprobe iwlwifi
		sudo modprobe iwlmld
		sudo modprobe btintel_pcie
		echo Enabled radios.
	else
		sudo modprobe -r btintel_pcie
		sudo modprobe -r iwlmld
		sudo modprobe -r iwlwifi
		echo Disabled radios.
	fi
elif [ "$1" = "nightlight" ]; then
	qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut "Toggle Night Color"
elif [ "$1" = "theme" ]; then
	# By default, toggles the theme and night light.
	# Themes trigger twice due to chromium bug not adjusting theme on first trigger.
	gx toggle nightlight
	current_theme=$(kreadconfig6 --group KDE --key LookAndFeelPackage)
	if [ "$current_theme" = "org.manjaro.breath-dark.desktop" ]; then
		lookandfeeltool -a org.manjaro.breath-light.desktop
		sleep 0.4
		lookandfeeltool -a org.manjaro.breath-light.desktop
		echo Enabled light theme.
	else
		lookandfeeltool -a org.manjaro.breath-dark.desktop
		sleep 0.4
		lookandfeeltool -a org.manjaro.breath-dark.desktop
		echo Enabled dark theme.
	fi
elif [ "$1" = "vpn" ]; then
	if systemctl -q is-active gilgamesh-31.ovpn; then
		gx vpn 45
		echo Enabled gilgamesh-45.ovpn.
	else
		gx vpn 31
		echo Enabled gilgamesh-31.ovpn.
	fi
fi
