#!/usr/bin/env bash
# Choose a VPN configuration and set up corresponding split tunnels, based on the provided systemd services.
if [ "$1" = "47" ]; then
	sudo systemctl stop gilgamesh-47.split.ovpn
	sudo systemctl stop gilgamesh-58.ovpn
	sudo systemctl start gilgamesh-47.ovpn
	sudo systemctl start gilgamesh-58.split.ovpn
elif [ "$1" = "58" ]; then
	sudo systemctl stop gilgamesh-47.ovpn
	sudo systemctl stop gilgamesh-58.split.ovpn
	sudo systemctl start gilgamesh-47.split.ovpn
	sudo systemctl start gilgamesh-58.ovpn
elif [ "$1" = "0" ]; then
	sudo systemctl stop gilgamesh-47.ovpn
	sudo systemctl stop gilgamesh-58.ovpn
	sudo systemctl start gilgamesh-47.split.ovpn
	sudo systemctl start gilgamesh-58.split.ovpn
fi
sleep 1
ping -c1 -W 2 1.1.1.1 | grep -B1 transmitted
ping -c1 -W 2 10.8.40.1 | grep -B1 transmitted
ping -c1 -W 2 10.8.47.1 | grep -B1 transmitted
ping -c1 -W 2 10.8.58.1 | grep -B1 transmitted
curl -m1 api.ipify.org
echo
curl -m1 api6.ipify.org
echo
