#!/usr/bin/env bash
# Proxy for `yt-dlp` with some defaults.
# Previously, we needed cookies to download on VPN. Currently, cookies are broken for some reason, raising a 403. Instead, we must use a residential proxy.
# --cookies-from-browser chromium+kwallet6 \
# Cookies may still bypass age restrictions sometimes.
yt-dlp \
	--js-runtimes node \
	--remote-components ejs:github \
	-f "bv[height>=720][filesize<1G] + ba[filesize < 100M] / b[filesize<1G] / wv[height>=720] + wa[filesize >= 100M] / wv + wa / w" \
	"$@"
