#!/usr/bin/env bash
# Proxy for `yt-dlp` with some defaults.
# Previously, we needed cookies to download on VPN. Currently, cookies are broken for some reason, raising a 403. Instead, we must use a residential proxy.
# --cookies-from-browser chromium+kwallet6 \
# Cookies may still bypass age restrictions sometimes.
yt-dlp \
	--js-runtimes node \
	--remote-components ejs:github \
	--cookies-from-browser chromium+kwallet6 \
	--output "%(uploader)s-%(title)s.%(ext)s" \
	--restrict-filenames \
	--windows-filenames \
	--format "bv[height>=720][vbr<=1024] + ba[abr<=128] / b[tbr<=1152] / wv[height>=720] + wa / wv + wa / w" \
	"$@"
