fs=yes
hwdec=auto
volume=70
profile=fast
save-position-on-quit
screenshot-template=mpv-%ts-%F-%ws
screenshot-directory=~/main.syncthing/snowfall/local.syncthing
screenshot-format=png
screenshot-png-compression=1
