fs=yes
hwdec=auto
volume=70
profile=fast
save-position-on-quit
screenshot-template=screenshot-%tY%tm%td%tH-%wH%wM%wS%wT-%F
screenshot-directory=~/main.syncthing/snowfall/local.syncthing
screenshot-format=png
screenshot-png-compression=0
# screenshot-directory=~/main.syncthing/snowfall
# screenshot-format=avif
# screenshot-avif-opts=crf=13,cpu-used=0
